<?php
try {
    // Abre (ou cria, se não existir) o banco de dados "meubanco.db"
    $db = new PDO('sqlite:BancoDeDados.db');
    $db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

    // Cria a tabela "alunos" com todos os campos
    $sql = "CREATE TABLE IF NOT EXISTS alunos (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        nomeFormAluno TEXT,
        dataNascimentoFormAluno TEXT,
        generoFormAluno TEXT,
        CPFFormAluno TEXT,
        possuiRG TEXT,
        RGFormAluno TEXT,
        emissorRGFormAluno TEXT,
        expedicaoRGFormAluno TEXT,
        nacionalidade TEXT,
        UF TEXT,
        naturalidade TEXT,
        raca TEXT,
        necessidadesFormAluno TEXT,
        tipoNecessidadesFormAluno TEXT,
        resticoesFormAluno TEXT,
        tiposRestricoesFormAlun TEXT,
        beneficioSocial TEXT,
        beneficioSocialFormAluno TEXT,
        NISFormAluno TEXT,
        nomeFormPai TEXT,
        dataNascimentoFormPai TEXT,
        naturalidadeFormPai TEXT,
        CPFFormPai TEXT,
        RGFormPai TEXT,
        emissorRGFormPai TEXT,
        expedicaoRGFormPai TEXT,
        telefoneFormPai TEXT,
        whatsappFormPai TEXT,
        profissaoFormPai TEXT,
        nomeFormMae TEXT,
        naturalidadeFormMae TEXT,
        dataNascimentoFormMae TEXT,
        CPFFormMae TEXT,
        RGFormMae TEXT,
        emissorRGFormMae TEXT,
        expedicaoRGFormMae TEXT,
        telefoneFormMae TEXT,
        whatsappFormMae TEXT,
        profissaoFormMae TEXT,
        estadoCivilFormPais TEXT,
        situacaoCivilFormPais TEXT,
        responsavelFormAluno TEXT,
        nomeFormResponsavel TEXT,
        parentescoFormResponsavel TEXT,
        CPFFormResponsavel TEXT,
        RGFormResponsavel TEXT,
        emissorRGFormResponsavel TEXT,
        expedicaoRGFormResponsavel TEXT,
        telefoneFormResponsavel TEXT,
        whatsappFormResponsavel TEXT,
        profissaoFormResponsavel TEXT,
        CEPFormAluno TEXT,
        ruaFormAluno TEXT,
        BairroFormAluno TEXT,
        cidadeFormAluno TEXT,
        situacaocasa TEXT,
        informacoesFormEscolaresAnterior TEXT,
        escolarFormEscola TEXT,
        escolarFormSerie TEXT,
        dadosFormTurno TEXT,
        anoMatricula TEXT,
        turnoMatricula TEXT,
        dataMatricula TEXT,
        dadosFormPlanoSaude TEXT,
        SUSFormMedicos TEXT,
        telefoneFormEmergencia TEXT,
        problemaSaude TEXT,
        qualProblemaSaude TEXT,
        medicamentoControlado TEXT,
        qualMedicamentoControlado TEXT,
        tratamento TEXT,
        qualTratamento TEXT,
        internado TEXT,
        qualMotivoInternacao TEXT,
        necessidadeEspecial TEXT,
        qualNecessidadeEspecial TEXT,
        atendimentoEspecializado TEXT,
        atendimentoEspecializadoSalaRecuso TEXT,
        parto TEXT,
        gestacao TEXT,
        gestacaoOcorrencia TEXT,
        acompanhadoCRAS TEXT,
        qualAcompanhadoCRAS TEXT,
        visitaSocial TEXT,
        visitaTutelar TEXT,
        atendimentoDomiciliar TEXT,
        transporteEscolar TEXT,
        usoImagem TEXT,
        sairSozinho TEXT,
        atividadeEstracurricular TEXT
    )";

    $db->exec($sql);
    echo "Tabela 'alunos' criada com sucesso!";
} catch(PDOException $e) {
    echo "Erro ao criar a tabela: " . $e->getMessage();
}
?>
